// AUTO-GENERATED by sync:functions. Do not edit.
import { evaluate7 } from '../evaluator.ts';
import { makeDeck, removeCards, type Card } from '../cards.ts';
import { handClassToCombos } from '../handNotation.ts';
import type { HandClass } from '../handNotation.ts';

/**
 * ヒーローの手 vs 相手レンジのエクイティを低反復MCで概算。
 * villainRange: HandClass -> weight（weight は相対確率）
 */
export function estimateEquityVsRange(
  hole: [Card, Card],
  board: Card[],
  villainRange: Record<string, number>,
  iterations = 1000,
  rng: () => number = Math.random,
): number {
  const handClasses = Object.keys(villainRange) as HandClass[];
  if (handClasses.length === 0) return 0.5;

  const totalWeight = handClasses.reduce((s, h) => s + (villainRange[h] ?? 0), 0);
  if (totalWeight === 0) return 0.5;

  // 既知のカードを除外したデッキ
  const knownCards = new Set<Card>([...hole, ...board]);

  let heroWins = 0;
  let trials = 0;

  for (let i = 0; i < iterations; i++) {
    // 相手レンジから重み付きサンプリング
    const villainHole = sampleFromRange(handClasses, villainRange, totalWeight, knownCards, rng);
    if (!villainHole) continue; // デッドコンボはスキップ

    // ボードを埋めるために残りカードのデッキを作成
    const usedCards = new Set<Card>([...hole, ...villainHole, ...board]);
    const remaining = removeCards(makeDeck(), usedCards);

    const need = 5 - board.length;
    if (need < 0) continue;

    // 残りボードをサンプリング（Fisher-Yates の先頭 need 枚）
    const deckCopy = remaining.slice();
    for (let k = 0; k < need; k++) {
      const j = k + Math.floor(rng() * (deckCopy.length - k));
      const tmp = deckCopy[k];
      deckCopy[k] = deckCopy[j];
      deckCopy[j] = tmp;
    }
    const runout = deckCopy.slice(0, need);
    const fullBoard: Card[] = [...board, ...runout];

    const heroVal = evaluate7([...hole, ...fullBoard]);
    const villainVal = evaluate7([...villainHole, ...fullBoard]);

    if (heroVal > villainVal) heroWins += 1;
    else if (heroVal === villainVal) heroWins += 0.5; // split

    trials++;
  }

  return trials === 0 ? 0.5 : heroWins / trials;
}

function sampleFromRange(
  handClasses: HandClass[],
  villainRange: Record<string, number>,
  totalWeight: number,
  knownCards: Set<Card>,
  rng: () => number,
): [Card, Card] | null {
  // 最大10回リトライ（デッドコンボを避けるため）
  for (let attempt = 0; attempt < 10; attempt++) {
    let r = rng() * totalWeight;
    let chosen: HandClass = handClasses[0];
    for (const hc of handClasses) {
      r -= villainRange[hc] ?? 0;
      if (r <= 0) { chosen = hc; break; }
    }

    // コンボを列挙して、既知カードと衝突しないものを選ぶ
    const combos = handClassToCombos(chosen).filter(
      ([c1, c2]) => !knownCards.has(c1) && !knownCards.has(c2),
    );
    if (combos.length === 0) continue;

    const combo = combos[Math.floor(rng() * combos.length)];
    return combo;
  }
  return null;
}
