// AUTO-GENERATED by sync:functions. Do not edit.
import { legalActions } from '../game/engine.ts';
import { decidePreflopAction } from './preflop.ts';
import { decidePostflopAction } from './postflop.ts';
import type { GameState, PlayerAction } from '../game/types.ts';

/**
 * CPU のアクションを決定する。
 * 必ず legalActions の範囲内のアクションを返す（不正な場合は最寄りの合法アクションへクランプ）。
 */
export function decideCpu(state: GameState, playerId: number): PlayerAction {
  try {
    const legal = legalActions(state, playerId);
    const rng = state.config.rng ?? Math.random;

    let action: PlayerAction;
    if (state.street === 'preflop') {
      action = decidePreflopAction(state, playerId, legal, rng);
    } else {
      action = decidePostflopAction(state, playerId, legal, rng);
    }

    return clampToLegal(action, legal, state);
  } catch {
    // フェイルセーフ: 例外が発生したらチェックかフォールド
    const legal = legalActions(state, playerId);
    if (legal.canCheck) return { type: 'check' };
    return { type: 'fold' };
  }
}

/** 返ってきたアクションが合法範囲内に収まるようにクランプする。 */
function clampToLegal(action: PlayerAction, legal: ReturnType<typeof legalActions>, state: GameState): PlayerAction {
  switch (action.type) {
    case 'fold':
      return { type: 'fold' };

    case 'check':
      if (!legal.canCheck) {
        // チェックできない場合: コール or フォールド
        if (legal.canCall) return { type: 'call' };
        return { type: 'fold' };
      }
      return { type: 'check' };

    case 'call':
      if (!legal.canCall) {
        if (legal.canCheck) return { type: 'check' };
        return { type: 'fold' };
      }
      return { type: 'call' };

    case 'bet':
      if (!legal.canBet) {
        // ベットできない（currentBet>0）→ raise に変換
        if (legal.canRaise) {
          const amt = clampAmount(action.amount ?? legal.minBetTo, legal.minBetTo, legal.maxBetTo);
          return { type: 'raise', amount: amt };
        }
        if (legal.canCall) return { type: 'call' };
        if (legal.canCheck) return { type: 'check' };
        return { type: 'fold' };
      }
      return { type: 'bet', amount: clampAmount(action.amount ?? legal.minBetTo, legal.minBetTo, legal.maxBetTo) };

    case 'raise':
      if (!legal.canRaise) {
        if (legal.canBet) {
          const amt = clampAmount(action.amount ?? legal.minBetTo, legal.minBetTo, legal.maxBetTo);
          return { type: 'bet', amount: amt };
        }
        if (legal.canCall) return { type: 'call' };
        if (legal.canCheck) return { type: 'check' };
        return { type: 'fold' };
      }
      return { type: 'raise', amount: clampAmount(action.amount ?? legal.minBetTo, legal.minBetTo, legal.maxBetTo) };

    case 'allin':
      return { type: 'allin' };

    default:
      if (legal.canCheck) return { type: 'check' };
      return { type: 'fold' };
  }
}

function clampAmount(amount: number, min: number, max: number): number {
  return Math.min(max, Math.max(min, amount));
}
