// AUTO-GENERATED by sync:functions. Do not edit.
import { getRfiRange } from './rfi.ts';
import { getVsOpen } from './vsOpen.ts';
import type { GameMode } from './mode.ts';
import type { Position, Range } from './types.ts';

/** RFI: `RFI_<pos>` / vsOpen: `VSOPEN_<opener>_<hero>`。 */
export type RangeKey = `RFI_${Position}` | `VSOPEN_${Position}_${Position}`;

export type CustomRanges = Partial<Record<RangeKey, Range>>;

export function rfiKey(pos: Position): RangeKey { return `RFI_${pos}`; }
export function vsOpenKey(opener: Position, hero: Position): RangeKey {
  return `VSOPEN_${opener}_${hero}`;
}

/** デフォルト導出（custom なし）。RFI は mode 依存、vsOpen は mode 非依存。 */
export function defaultRange(key: RangeKey, mode: GameMode): Range | undefined {
  if (key.startsWith('RFI_')) {
    const pos = key.slice(4) as Position;
    return getRfiRange(mode, pos);
  }
  // VSOPEN_<opener>_<hero>
  const [, opener, hero] = key.split('_') as [string, Position, Position];
  return getVsOpen(hero, opener)?.range;
}

/** custom があれば優先、無ければデフォルト導出。 */
export function getEffectiveRange(
  key: RangeKey,
  mode: GameMode,
  custom?: CustomRanges,
): Range | undefined {
  const c = custom?.[key];
  if (c && Object.keys(c).length > 0) return c;
  return defaultRange(key, mode);
}
