// AUTO-GENERATED by sync:functions. Do not edit.
import { RFI_SCENARIOS, getRfiScenarios, getRfiRange } from './rfi.ts';
import type { GameMode } from './mode.ts';
import type { Scenario } from './types.ts';

export * from './types.ts';
export * from './expand.ts';
export * from './mode.ts';
export * from './yokosawa.ts';
export * from './vsOpen.ts';
export * from './seats.ts';
export * from './effective.ts';
export { RFI_SCENARIOS, getRfiScenarios, getRfiRange };

export const ALL_SCENARIOS: Scenario[] = [...RFI_SCENARIOS]; // tournament 既定（後方互換）

/** id で scenario を取得（既定モード tournament）。後方互換のため残す。 */
export function getScenario(id: string): Scenario | undefined {
  return ALL_SCENARIOS.find((s) => s.id === id);
}

/** モード指定で scenario を取得。 */
export function getScenarioForMode(id: string, mode: GameMode): Scenario | undefined {
  return getRfiScenarios(mode).find((s) => s.id === id);
}
